title: Infinite-Dimensional Spectral Computations
description: Supplementary material for the book Infinite-Dimensional Spectral Computations.

url: "https://spectralcomputations.org"
baseurl: ""

markdown: kramdown

