title: Spectral Computations
description: Numerical methods and spectral analysis
theme: null

markdown: kramdown

# Ensure Jekyll uses custom layouts
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
